# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 910451e434c8e763a296eecbcd45a72e4e22f4ccc5b36fb0b0ff9386e5017610b95072916fb71e3c9c35faf985a6107b0d69cf4b23a82bd002557d11ec779d31

test:
  secret_key_base: 9b7800befb8cc92d7a74d5f6859cef338861e38e3a1c29a34e2c9b93175bc928d673a9b62005559080431df46b8d4ca68b815bee283b51cb10f75eb086eb2223
 
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 01bef6709bfd70307b1171bc743c9898b78bd30457c84ebf7303a9891fc221ab69d4c500c4eebeb72aae2a6d409af9c4024dd9b94d1fdf2fb765d3cace74c6ab
